document:
  name: Guida all'implementazione del SDK Mobile CIE id
  description: |
    Guida operativa all'implementazione del SDK Mobile CIE id che consente l'integrazione dello schema di autenticazione "Entra con CIE" all'interno di Applicazioni mobile dei fornitori di servizi abilitati. 
  tags:
    - standard 
    - interoperabilità
    - cie
    - sdk
  
